# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: de85f48434a29f6b6e01b163e11d3296cc2b0b7aef7dcdb964722d74ccccba0c825daa4cd2072a3faea672c8386096760cf420bb3473bdc5591b066fa9cca125

test:
  secret_key_base: 0d2024120cbb26b21fadffd700c721cf8724f73977822a1a9b03770f2d11afda60470e8efd7e5d497a0452fa89d28337b2268d547862e2d926d341829985b616

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
